### ISSUE TITLE
gclone: command not found

### ISSUE THREAD

**Issue by Lukasz88PL** [xd003/easyclone#9]
Script doesn't work after new update. I checked 3 options and none worked, so I guess every command right now doesnt work. 

/usr/bin/clone: line 140: gclone: command not found
/usr/bin/clone: line 296: gclone: command not found
/usr/bin/clone: line 260: gclone: command not found

**Comment by xd003** [comment]
Should be fine now, can you please confirm ?

**Comment by Pablobot003** [comment]
> Should be fine now, can you please confirm ?

Still not working. /data/data/com.termux/files/usr/bin/clone: line 372: gclone: command not found

**Comment by Lukasz88PL** [comment]
yep, it works now
